# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'connect-nm'
    namespace: 'Nicolas-AKS'
    command: 'top'
    arguments: 'pod'

- task: Cache@2
  inputs:
    key: '12345'
    path: '/home/vsts/version'
    cacheHitVar: 'cachette'

- task: CmdLine@2
  inputs:
    script: |
      cat /home/vsts/version/version.vote
      mkdir /home/vsts/version
      pwd
      curl ''https://hub.docker.com/v2/repositories/simplonasa/azure_voting_app/tags'' | jq '."results"[0]["name"]'>/home/vsts/version/version.vote
      cat /home/vsts/version/version.vote
- task: Cache@2
  inputs:
    key: '12345'
    path: '/home/vsts/version'
    cacheHitVar: 'cachette'