apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nm-volume
provisioner: kubernetes.io/azure-disk
parameters:
  skuName: Standard_LRS
allowVolumeExpansion: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nm-vol
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  storageClassName: nm-volume
