apiVersion : applications/v1
genre : Déploiement
métadonnées :
  nom : vote app
  étiquettes :
    application : voteapplb
spécification :
  sélecteur :
    matchLabels :
      application : voteapplb
  répliques : 2
  modèle :
    métadonnées :
      étiquettes :
        application : voteapplb
    spécification :
      conteneurs :
      - nom : voteapp
        image : simplonasa/azure_voting_app  :{{ version }}
        image : simplonasa/azure_voting_app :{{ version }}
        ports :
        - Port conteneur : 80
        env :
        - nom : REDIS
          valeur : cluster
        - nom : STRESS_SECS
          valeur : " 2 "
        - nom : redispwd
          valueFrom :
            secretKeyRef :
              nom : redis
              clé : REDIS_PASS
---
apiVersion : v1
genre : Service
métadonnées :
  nom : vote app
spécification :
  type : Cluster IP
  ports :
  - port : 80
  sélecteur :
    application : voteapplb
---
apiVersion : applications/v1
genre : Déploiement
métadonnées :
  nom : redis
  étiquettes :
    application : redis-bd
spécification :
  sélecteur :
    matchLabels :
      application : redis-bd
  répliques : 1
  modèle :
    métadonnées :
      étiquettes :
        application : redis-bd
    spécification :
      tomes :
      - nom : redis-vol
        persistentVolumeClaim :
          nom_réclamation : nm-vol
      conteneurs :
      - nom : redis
        image : redis
        arguments : [" --requirepass ","$(REDIS_PASS)"]
        env :
        - nom : ALLOW_EMPTY_PASSWORD
          valeur : " non "
        - nom : REDIS_PASS
          valueFrom :
            secretKeyRef :
              nom : redis
              clé : REDIS_PASS
        ports :
        - port conteneur : 6379
          nom : redis
        volumeMounts :
        - nom : redis-vol
          mountPath : " /data "
---
apiVersion : v1
genre : Service
métadonnées :
  nom : cluster
spécification :
  type : Cluster IP
  ports :
  - port : 6379
  sélecteur :
    application : redis-bd
---
apiVersion : networking.k8s.io/v1
genre : Entrée
métadonnées :
  nom : vote d'entrée
  annotations :
    kubernetes.io/ingress.class : azure/application-gateway
spécification :
  tl :
    - nomsecret : nm-tls
  règles :
  - http :
      chemins :
      - pathType : Préfixe
        chemin : /
        back -end :
          service :
            nom : vote app
            ports :
              nombre : 80
---
apiVersion : mise à l' échelle automatique/v1
type : HorizontalPodAutoscaler
métadonnées :
  nom : scale app
spécification :
  maxRépliques : 8
  minRépliques : 2
  scaleTargetRef :
    apiVersion : applications/v1
    genre : Déploiement
    nom : vote app
  Pourcentage d'utilisation du processeur cible : 70
